import React from 'react';
import { FileCheck, Info, CheckCircle, Copy, RefreshCw } from 'lucide-react';

export default function ReportDashboard({ analysisResult, onReset, copiedStatus, handleCopyText }) {
  const getSeverityBadgeColor = (severity) => {
    switch (severity?.toLowerCase()) {
      case 'high':
        return 'bg-red-500/15 text-red-400 border border-red-500/30';
      case 'medium':
        return 'bg-amber-500/15 text-amber-400 border border-amber-500/30';
      case 'low':
        return 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30';
      default:
        return 'bg-zinc-700/50 text-zinc-300';
    }
  };

  const getOverallRiskDetails = (score) => {
    if (score >= 70) return { color: 'text-red-500', barColor: 'bg-red-500', label: 'Severe Exposure' };
    if (score >= 40) return { color: 'text-amber-500', barColor: 'bg-amber-500', label: 'Moderate Caution' };
    return { color: 'text-emerald-500', barColor: 'bg-emerald-500', label: 'Minimal Threat' };
  };

  const threatDetails = getOverallRiskDetails(analysisResult.score);

  return (
    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6 shadow-2xl flex-1 flex flex-col animate-fadeIn">
      {/* Report Header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between border-b border-zinc-800 pb-6 mb-6 gap-4">
        <div>
          <button 
            onClick={onReset}
            className="text-indigo-400 text-xs hover:text-indigo-300 transition duration-150 flex items-center gap-1.5 mb-2 cursor-pointer"
          >
            ← Upload different contract
          </button>
          <h3 className="text-xl font-bold text-white flex items-center gap-2">
            <FileCheck className="h-5.5 w-5.5 text-indigo-400" />
            Scan Audit Report
          </h3>
          <p className="text-xs text-zinc-400">Risk Assessment generated by AI Contract Engine</p>
        </div>

        <div className="bg-zinc-950 px-4 py-3 rounded-xl border border-zinc-800/80 flex items-center gap-4 shrink-0">
          <div className="text-center">
            <span className="block text-[10px] uppercase font-bold text-zinc-500 tracking-wider">Risk Score</span>
            <span className={`text-2xl font-black ${threatDetails.color}`}>
              {analysisResult.score}/100
            </span>
          </div>
          <div className="h-8 w-[1px] bg-zinc-800" />
          <div className="text-left">
            <span className="block text-[10px] uppercase font-bold text-zinc-500 tracking-wider">Classification</span>
            <span className={`text-sm font-extrabold ${threatDetails.color}`}>
              {analysisResult.verdict}
            </span>
          </div>
        </div>
      </div>

      {/* Summary Block */}
      <div className="mb-6 bg-zinc-950 border border-zinc-800/60 p-4 rounded-xl flex items-start gap-3">
        <Info className="h-5 w-5 text-indigo-400 shrink-0 mt-0.5" />
        <div>
          <span className="font-bold text-sm block text-white mb-1">Executive Summary</span>
          <p className="text-xs text-zinc-400 leading-relaxed">
            {analysisResult.summary}
          </p>
        </div>
      </div>

      {/* Visualized Score Bar */}
      <div className="mb-6">
        <div className="flex justify-between text-xs font-bold text-zinc-400 mb-2">
          <span>Exposure Threat Level</span>
          <span>{threatDetails.label}</span>
        </div>
        <div className="w-full bg-zinc-950 h-3 rounded-full overflow-hidden border border-zinc-800 p-[2px]">
          <div 
            className={`h-full rounded-full transition-all duration-1000 ${threatDetails.barColor}`}
            style={{ width: `${analysisResult.score}%` }}
          />
        </div>
      </div>

      {/* Risks List */}
      <h4 className="text-sm font-extrabold uppercase text-zinc-400 tracking-wider mb-3">
        Flagged Clauses & Alterations ({analysisResult.risks?.length || 0})
      </h4>

      <div className="flex-1 overflow-y-auto custom-scroll space-y-4 pr-1 max-h-[550px]">
        {analysisResult.risks && analysisResult.risks.length > 0 ? (
          analysisResult.risks.map((risk, idx) => (
            <div key={idx} className="bg-zinc-950/80 border border-zinc-800 hover:border-zinc-700/80 transition duration-200 rounded-xl p-4 flex flex-col gap-3 relative overflow-hidden">
              <div className="flex items-center justify-between gap-3 flex-wrap">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold px-2 py-0.5 rounded-full bg-zinc-800 border border-zinc-700 text-zinc-300">
                    {risk.category}
                  </span>
                  <span className={`text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded-full ${getSeverityBadgeColor(risk.severity)}`}>
                    {risk.severity} Threat
                  </span>
                </div>
              </div>

              <div className="bg-zinc-900/40 p-3 rounded-lg border border-zinc-900 text-xs">
                <span className="block text-[10px] text-zinc-500 font-bold uppercase tracking-wider mb-1">Found Text Excerpt:</span>
                <p className="italic text-zinc-300 leading-relaxed font-mono">
                  "{risk.clause}"
                </p>
              </div>

              <div>
                <span className="block text-[10px] text-zinc-500 font-bold uppercase tracking-wider mb-1">Business Impact:</span>
                <p className="text-xs text-zinc-400 leading-relaxed">
                  {risk.implication}
                </p>
              </div>

              <div className="bg-indigo-950/15 p-3.5 rounded-lg border border-indigo-900/30">
                <div className="flex items-center justify-between mb-1.5">
                  <span className="block text-[10px] text-indigo-400 font-bold uppercase tracking-wider">Suggested Alteration (Redline Proposal):</span>
                  <button
                    onClick={() => handleCopyText(risk.suggestedAlteration, `alt-${idx}`)}
                    className="text-indigo-400 hover:text-indigo-300 p-1 rounded hover:bg-indigo-900/30 transition duration-150 cursor-pointer flex items-center gap-1 text-[10px]"
                    title="Copy Suggestion"
                  >
                    <Copy className="h-3.5 w-3.5" />
                    <span>{copiedStatus[`alt-${idx}`] ? 'Copied!' : 'Copy'}</span>
                  </button>
                </div>
                <p className="text-xs text-indigo-300 font-mono leading-relaxed bg-indigo-950/40 p-2.5 rounded border border-indigo-950/80">
                  {risk.suggestedAlteration}
                </p>
              </div>
            </div>
          ))
        ) : (
          <div className="text-center py-8 bg-zinc-950 rounded-xl border border-zinc-800">
            <CheckCircle className="h-8 w-8 text-emerald-400 mx-auto mb-2" />
            <p className="text-sm font-bold text-white">No major legal risks identified</p>
            <p className="text-xs text-zinc-500 px-4 mt-1">This agreement contains fair terms aligned with common industry parameters.</p>
          </div>
        )}
      </div>

      <div className="mt-6 pt-4 border-t border-zinc-800 flex justify-end">
        <button
          onClick={onReset}
          className="bg-zinc-800 hover:bg-zinc-700 text-white font-bold py-2.5 px-5 rounded-xl text-xs transition duration-200 cursor-pointer flex items-center gap-2"
        >
          <RefreshCw className="h-4.5 w-4.5" />
          Analyze Another Contract
        </button>
      </div>
    </div>
  );
}